from allpairspy import AllPairs

# Parametreler
parameters = [
    ["Yoga", "Boxing", "Fitness", "Basketball", "Tennis", "Swimming"], # Activity
    [9, 14, 19],          # Hours (Morning, Day, Evening)
    ["Standard", "Premium", "Student"] # Membership
]

print("--- PAIRWISE TEST SET (Generated by allpairspy) ---")
print(f"{'Activity':<12} | {'Hour':<5} | {'Membership':<10}")
print("-" * 35)

# Pairwise algoritmasını çalıştır
for i, pairs in enumerate(AllPairs(parameters)):
    act, hour, mem = pairs
    print(f"{act:<12} | {hour:<5} | {mem:<10}")

print("-" * 35)